### PR TITLE
Add tech content, images and fixed HTML structure

### PR DESCRIPTION
**Pull request by xredo**
## Changes

- Fixed HTML structure.
- Added technical details of the implementation.
- Added images. Thanks @marinaaisa for creating the cool backgrounds 🙌
- Added a new quote. I believe it's a good idea to add also quotes from MarsBased team to highlight important aspects of the project.
- Added time to Market label on the top of the project. I think it could be interesting to potential clients.

## Pending work

@alexrodba, It's important that you review the texts that I've written. I'm still ill and my writing is not as fluent as usual.

Now that I have added my part, maybe you would want to rewrite some sentences where we are constantly repeating that we used Ruby on Rails.

@jvendrell I'm adding you as a reviewer also to make some quality assessment of this portfolio.

### CODE REVIEW

**Comment by jvendrell** [comment]
Hey @alexrodba, @xredo:

It's wonderful. I like it very much. Awesome job.

Just one thing. I'll move this portfolio to master manually because this branch is very old and it lacks some major changes that we did. If we try to merge it automatically it will be a mess.

Just don't do any merging. Let me know whenever it's finished and I'll publish it myself.

**Comment by alexrodba** [comment]
Great job, @xredo.

I've added the following changes:

- Added some changes requested by Barcelona Activa.
- Xavi, it's cool to be the main developer of the project, but you're CTO & Co-founder. We'll use "main developer" for the rest of the team.
- Rephrased a couple of sentences here and there.
- Added "title" attributes to links entered by Xavi.

And suggest one change:

- I find the title to be very small, ain't it? Can't we increase the size to highlight it more?
image

I find that the "related work entries" is broken, or is it just me?

I've just sent it again to Itziar for review, so wait before you publish, Jordi :)

**Comment by jvendrell** [comment]
@xredo @alexrodba:

I've moved the portfolio to another branch which can be merged to master more easily:

https://github.com/MarsBased/marsbased-website/pull/51

@alexrodba:

- For coherence, the Barcelona Startup Map title can't be bigger. This type of heading appears in other pages with the same size.
- The /work page had a Lorem Ipsum subtitle. I've replaced it for something of my own. You will probably want to review that copy.
- Related Works is working properly in the branch that I've created from the current master. However, I deactivated the section until we have more portfolios.
- From my point of view, it's ready to be published.

**Comment by alexrodba** [comment]
@jvendrell looks good to me. Your text will do, for now. I'll let you know when we receive the OK from BCN Activa and we can publish this one.

**Pull request closed without merging**
